apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-CI-logs
        image: sha256:84a97bXXXXXXXXXXXXXXXXXXXXXXXXXX
        ports:
        - containerPort: 8080
